---

- name: import rabbitmq main key
  become: true
  command: 'apt-key adv --keyserver "hkps://keys.openpgp.org" --recv-keys "0x0A9AF2115F4687BD29803A206B73A36E6026DFCA"'

- name: import launchpad key
  become: true
  command: 'apt-key adv --keyserver "keyserver.ubuntu.com" --recv-keys "F77F1EDA57EBB1CC"'

- name: import packagecloud key
  become: true
  command: 'apt-key adv --keyserver "keyserver.ubuntu.com" --recv-keys "F6609E60DC62814E"'

- name: Install Erlang
  import_role:
    name: deps/rockandska/ansible-role-erlang
  become: yes

- include: install.deb.yml

- name: Ensure RabbitMQ is running
  service:
    name: rabbitmq-server
    state: started

- name: Ensure the users is removed
  community.rabbitmq.rabbitmq_user:
    user: "{{item}}"
    state: absent
  with_items: "{{rabbitmq_users_remove}}"

- name: Ensure the vhosts is present
  community.rabbitmq.rabbitmq_vhost:
    name: "{{item}}"
  with_items: "{{rabbitmq_vhosts}}"

- name: Ensure the users is present
  community.rabbitmq.rabbitmq_user:
    user: "{{item.user}}"
    password: "{{item.password}}"
    configure_priv: "{{item.configure_priv|default('.*')}}"
    read_priv: "{{item.read_priv|default('.*')}}"
    write_priv: "{{item.write_priv|default('.*')}}"
    vhost: "{{item.vhost|default('/')}}"
    tags: "{{item.tags|default('')}}"
  with_items: "{{rabbitmq_users}}"

- name: Symlink RabbitMQ sbin to bin
  file:
    state: link
    src: "/usr/sbin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
  with_items:
    - rabbitmq-diagnostics
    - rabbitmq-plugins
    - rabbitmq-queues
    - rabbitmq-server
    - rabbitmq-upgrade
    - rabbitmqctl

- name: Enable the plugins is installed
  community.rabbitmq.rabbitmq_plugin:
    names: "{{item}}"
    state: enabled
    prefix: /usr
  with_items: "{{rabbitmq_plugins}}"
  notify:
    - rabbitmq restart

- name: Ensure rabbitmq directory exists
  become: yes
  file:
    path: /etc/rabbitmq
    state: directory
    owner: rabbitmq
    group: rabbitmq

- name: Generate the configuration of rabbitmq
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
    owner: rabbitmq
    group: rabbitmq
    mode: 0644
    backup: yes
  notify: rabbitmq restart
